// <auto-generated />
using System;
using Ball_Game_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ball_Game_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ball_Game_API.Data.ScoreHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Player1Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Player1Score")
                        .HasColumnType("integer");

                    b.Property<string>("Player2Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Player2Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ScoreHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
